name: Hourly Run Trading Economics Calendar

on:
  push:
    branches:
      - main # Runs on push to the main branch
  schedule:
    - cron: '0 * * * *'  # Runs every hour


jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Use v3 for the latest version

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.2'  # Use the specific version of Python you need

    - name: Install dependencies manually
      run: |
        pip install pandas
        pip install numpy
        pip install selenium
        pip install bs4
        
    - name: Run Python script
      run: python event_calendar_runner_main.py  # Replace with your actual Python script name

    - name: Configure Git user
      run: |
        git config --global user.name "krishangguptafibonacciresearch"  # Replace with your name
        git config --global user.email "krishanggupta@fibonacciresearch.in"  # Replace with your email

    - name: Check if both folders have files and commit changes
      run: |
       
        git add .
        git commit -m "Calendar Updated"
        git push
       
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
